services:
  python-api:
    image: python:3.13-slim
    working_dir: /app
    command: ["sh", "-lc", "pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    volumes:
      - ./python-api:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).status == 200 else sys.exit(1)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  node-api:
    image: node:22-alpine
    working_dir: /app
    command: ["node", "src/index.js"]
    environment:
      - PY_BASE=http://python-api:8000
    volumes:
      - ./node-api:/app
    ports:
      - "3000:3000"
    depends_on:
      python-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://127.0.0.1:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
