services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - SESSION_SECRET=${SESSION_SECRET:-devsupersecret}
      - DB_PATH=/app/data/app.db
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - db_data:/app/data
    ports:
      - "8000:8000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=http://api:8000
      - SESSION_SECRET=${SESSION_SECRET:-devsupersecret}
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:

