FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8000

ENV SESSION_SECRET=devsupersecret \
    CORS_ORIGINS=http://localhost:3000 \
    DB_PATH=/app/data/app.db

RUN mkdir -p /app/data && chmod -R 777 /app/data

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
